Added C++ implementation to the first 3 sum_of_squares files
OU-CS3560/examples pull request #150
Opened 2021-03-17 00:37 UTC by BradeyLounsbury

I tried to keep the output as close to the original files as possible but I think the time functions available with C++ aren't as precise as the time functions in python so the data output from the C++ files are only out to 6 decimal places.

Also, the C++ implementations seemed to scale linearly whereas the python implementation were exponential.  With lower max values, python was faster but as the max increased, C++ began to close the gap until it eventually surpassed python.

2021-03-17 03:50 UTC, krerkkiat requested changes
Please make sure that the source code can be compiled on school linux server. Note that `SumOfPerfectSquares-math.cc` is introduced in #145 already,.

2021-03-17 03:50 UTC, krerkkiat commented on sum_of_squares/SumOfPerfectSquares-dp-static.cc
> +        g_count.push_back(INT_MAX);
This file cannot be compiled on the school linux server. Could you please double check?

2021-03-17 03:50 UTC, krerkkiat commented on sum_of_squares/SumOfPerfectSquares-dp.cc
> +        g_count.push_back(INT_MAX);
This file cannot be compiled on the school linux server. Could you please double check?

2021-03-17 03:50 UTC, krerkkiat commented on sum_of_squares/SumOfPerfectSquares-math.cc
> +#include <iostream>
Note that there is already a translation for this version which is introduced by #145

2021-03-18 04:02 UTC, krerkkiat commented
another dynamic programming version introduced in #169

2021-03-18 04:44 UTC, BradeyLounsbury commented
I got an compilation error saying INT_MAX wasn't defined so I changed that and it should compile now

2021-03-18 06:18 UTC, merged